# Generated by Django 4.2.6 on 2023-11-15 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_brand_created_at_brand_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='categories/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
