# Generated by Django 4.2.7 on 2023-11-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_order_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cart_itmes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
    ]
