# Generated by Django 4.2.7 on 2023-11-22 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('backend', '0013_alter_reviews_unique_together_remove_cart_itmes_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_itmes',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='authentication.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('user', 'product')},
        ),
    ]
