# Generated by Django 4.2.7 on 2023-11-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_variation_delete_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
