# Generated by Django 4.2.6 on 2023-11-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_veriationscategory_product_variations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='variation_category',
        ),
    ]
