# Generated by Django 4.2.6 on 2023-11-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_remove_variation_variation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.veriationscategory'),
        ),
    ]
