# Generated by Django 4.2.6 on 2023-11-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_variation_variation_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='variations',
            new_name='has_variations',
        ),
    ]
