# Generated by Django 4.2.7 on 2023-12-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_rename_variations_product_has_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='parentCategory/images'),
        ),
    ]
