# Generated by Django 4.2.6 on 2023-12-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitmes',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
